description   = "Concept drift scenario with artificial drift via parameter modification"
source_type   = "sklearn"
source_name   = "make_classification"
target_column = "target"
drift_types   = ["concept"]

[ground_truth]
    drift_periods   = [[500, 1000]]
    drift_intensity = "moderate"

[ref_filter]
    sample_range = [0, 500]
    # Reference data generation parameters
    n_samples     = 1000 # Generate 1000 total samples
    n_features    = 10 # 10 features
    n_informative = 8 # 8 informative features
    random_state  = 42

[test_filter]
    sample_range = [500, 1000]
    # Test data generation with artificial concept drift
    n_samples     = 1000 # Generate 1000 total samples
    n_features    = 10 # 10 features
    n_informative = 8 # 8 informative features
    concept_shift = true # Enable artificial concept drift
    random_state  = 43 # Different random state for concept drift
