description   = "Concept drift scenario with known ground truth"
source_type   = "sklearn"
source_name   = "make_classification"
target_column = "target"
drift_types   = ["concept"]

[ground_truth]
    drift_periods   = [[500, 1000]]
    drift_intensity = "moderate"

[ref_filter]
    sample_range = [0, 500]

[test_filter]
    sample_range  = [500, 1000]
    concept_shift = true
