description   = "Covariate drift scenario with artificial drift via noise injection"
source_type   = "sklearn"
source_name   = "make_classification"
target_column = "target"
drift_types   = ["covariate"]

[ground_truth]
    drift_periods   = [[500, 1000]]
    drift_intensity = "moderate"

[ref_filter]
    sample_range = [0, 500]
    # Reference data generation parameters
    n_samples    = 1000 # Generate 1000 total samples
    n_features   = 10 # 10 features
    noise_factor = 1.0 # Standard noise level
    random_state = 42

[test_filter]
    sample_range = [500, 1000]
    # Test data generation with artificial covariate drift
    n_samples    = 1000 # Generate 1000 total samples
    n_features   = 10 # 10 features
    noise_factor = 1.5 # Higher noise to simulate covariate drift
    random_state = 42
