description   = "Simple CSV data scenario for basic testing"
source_type   = "file"
source_name   = "example.csv"
target_column = "RainTomorrow"
drift_types   = ["covariate"]

[ground_truth]
    drift_periods   = [[30, 50]]
    drift_intensity = "mild"

[ref_filter]
    sample_range = [0, 30]

[test_filter]
    sample_range = [30, 50]
