description   = "Breast cancer dataset with authentic covariate drift via feature-based filtering"
source_type   = "sklearn"
source_name   = "load_breast_cancer"
target_column = "target"
drift_types   = ["covariate"]

[ground_truth]
    drift_periods   = [[0, 569]] # Drift through feature-based sampling creates authentic drift
    drift_intensity = "moderate"

[ref_filter]
    # Reference data: smaller tumors (authentic low-risk population)
    sample_range = [0, 569] # Use all samples, filter by features
    feature_filters = [
        { column = "mean radius", condition = "<=", value = 14.0 },
        { column = "mean texture", condition = "<=", value = 20.0 },
    ]

[test_filter]
    # Test data: larger tumors (authentic high-risk population)
    sample_range = [0, 569] # Use all samples, filter by features  
    feature_filters = [
        { column = "mean radius", condition = ">", value = 14.0 },
        { column = "mean texture", condition = ">", value = 20.0 },
    ]
