description   = "Diabetes regression dataset with authentic covariate drift via feature-based filtering"
source_type   = "sklearn"
source_name   = "load_diabetes"
target_column = "target"
drift_types   = ["covariate"]

[ground_truth]
    drift_periods   = [[0, 442]] # Drift through feature-based sampling creates authentic drift
    drift_intensity = "mild"

[ref_filter]
    # Reference data: patients with lower BMI and age (authentic low-risk population)
    sample_range = [0, 442] # Use all samples, filter by features
    feature_filters = [
        { column = "bmi", condition = "<=", value = 0.0 },
        { column = "age", condition = "<=", value = 0.0 },
    ]

[test_filter]
    # Test data: patients with higher BMI and age (authentic high-risk population)  
    sample_range = [0, 442] # Use all samples, filter by features
    feature_filters = [
        { column = "bmi", condition = ">", value = 0.0 },
        { column = "age", condition = ">", value = 0.0 },
    ]
