description   = "Synthetic regression with artificial concept drift via parameter modification"
source_type   = "sklearn"
source_name   = "make_regression"
target_column = "target"
drift_types   = ["concept"]

[ground_truth]
    drift_periods   = [[400, 800]] # Middle section has artificial concept drift
    drift_intensity = "severe"

[ref_filter]
    sample_range = [0, 400] # First 400 samples as reference
    # Reference data generation parameters
    n_samples     = 800 # Generate 800 total samples
    n_features    = 5 # 5 features
    n_informative = 5 # All features informative
    noise         = 0.1 # Low noise level
    random_state  = 42

[test_filter]
    sample_range = [400, 800] # Next 400 samples as test
    # Test data generation with artificial concept drift
    n_samples     = 800 # Generate 800 total samples
    n_features    = 5 # 5 features
    n_informative = 5 # All features informative
    noise         = 0.4 # Higher noise to simulate concept drift
    concept_shift = true # Enable artificial concept drift
    random_state  = 43 # Different random state for drift
