description   = "Iris classification dataset with authentic concept drift via class-based filtering"
source_type   = "sklearn"
source_name   = "load_iris"
target_column = "target"
drift_types   = ["concept"]

[ground_truth]
    drift_periods   = [[0, 150]] # Drift through class-based filtering creates authentic concept drift
    drift_intensity = "severe"

[ref_filter]
    # Reference data: balanced mix of classes (authentic multi-class distribution)
    sample_range    = [0, 150] # Use all samples, filter by features
    feature_filters = [{ column = "petal length (cm)", condition = "<=", value = 4.5 }]

[test_filter]
    # Test data: focus on larger flowers (authentic class imbalance)
    sample_range    = [0, 150] # Use all samples, filter by features  
    feature_filters = [{ column = "petal length (cm)", condition = ">", value = 4.5 }]
