# REQ-DAT-008: Synthetic source type scenario (using sklearn synthetic datasets)
# REQ-DAT-026: Complete TOML schema with required fields
description   = "Synthetic covariate drift scenario for basic testing"
source_type   = "synthetic"
source_name   = "classification"
target_column = "target"
drift_types   = ["covariate"]

[ref_filter]
    sample_range = [0, 99]
    random_state = 42

[test_filter]
    sample_range = [100, 199]
    noise_factor = 0.5 # Modification parameter for synthetic

[ground_truth]
    drift_periods        = [[100, 199]]
    drift_intensity      = "moderate"
    expected_effect_size = 0.4
    minimum_power        = 0.8
