# No-drift baseline scenario with UCI data
description   = "UCI Iris baseline scenario with no drift for statistical comparison"
source_type   = "uci"
source_name   = "iris"
target_column = "species"
drift_types   = ["none"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = []
    drift_intensity      = "none"
    expected_effect_size = 0.0
    kl_divergence        = 0.0
    expected_detection   = false
    drift_confidence     = 0.0

# Statistical validation for false positive rate testing
[statistical_validation]
    expected_effect_size = 0.0
    minimum_power        = 0.80
    significance_level   = 0.05
    baseline_scenario    = "no_drift_uci"

# Reference data: first half of dataset
[ref_filter]
    sample_range = [0, 75]

# Test data: second half of dataset (no feature filtering)
[test_filter]
    sample_range = [75, 150]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 150
    feature_descriptions = [
        "sepal_length: Sepal length in cm",
        "sepal_width: Sepal width in cm",
        "petal_length: Petal length in cm",
        "petal_width: Petal width in cm",
        "species: Iris species (setosa, versicolor, virginica)",
    ]
    data_quality_score = 1.0
    data_authenticity = "real"
    scientific_traceability = true

# UCI metadata for scientific traceability
[uci_metadata]
    dataset_id             = "iris"
    domain                 = "biology_botany"
    original_source        = "R.A. Fisher"
    acquisition_date       = "1936-01-01"
    collection_methodology = "Manual measurement of iris flowers"
    data_authenticity      = "real"
    total_instances        = 150
