# Online and Streaming Comprehensive Configuration
# All available online/streaming drift detection methods
# Focus on real-time drift detection with sequential data processing

# Scenarios suitable for streaming analysis
[[scenarios]]
    id = "synthetic/concept_drift_gradual"

[[scenarios]]
    id = "synthetic/covariate_drift_strong"

[[scenarios]]
    id = "custom/sensor_data_drift"

[[scenarios]]
    id = "custom/customer_churn"

# === RIVER ADAPTIVE METHODS ===
[[detectors]]
    method_id  = "adaptive_windowing"
    variant_id = "adwin_standard"
    library_id = "river"
    delta      = 0.002

# === RIVER STATISTICAL PROCESS CONTROL ===
[[detectors]]
    method_id     = "drift_detection_method"
    variant_id    = "ddm_standard"
    library_id    = "river"
    warning_level = 2.0
    drift_level   = 3.0

[[detectors]]
    method_id     = "early_drift_detection_method"
    variant_id    = "eddm_standard"
    library_id    = "river"
    warning_level = 0.95
    drift_level   = 0.90

# === RIVER CHANGE DETECTION METHODS ===
[[detectors]]
    method_id  = "page_hinkley"
    variant_id = "ph_standard"
    library_id = "river"
    delta      = 0.005
    lambda     = 50.0
    alpha      = 0.9999

[[detectors]]
    method_id       = "cusum"
    variant_id      = "cusum_standard"
    library_id      = "river"
    threshold       = 0.5
    drift_threshold = 1.0

[[detectors]]
    method_id  = "geometric_moving_average"
    variant_id = "gma_standard"
    library_id = "river"
    lambda     = 0.1
    threshold  = 0.5

[[detectors]]
    method_id  = "exponential_cumulative_drift"
    variant_id = "ecdd_standard"
    library_id = "river"
    lambda     = 0.1
    threshold  = 0.5

[[detectors]]
    method_id         = "ewma_concept"
    variant_id        = "ewma_standard"
    library_id        = "river"
    lambda            = 0.1
    warning_threshold = 2.0
    drift_threshold   = 3.0

# === RIVER HOEFFDING-BASED METHODS ===
[[detectors]]
    method_id  = "hoeffding_drift_detection_test_a"
    variant_id = "hddm_a_standard"
    library_id = "river"
    delta      = 0.002

[[detectors]]
    method_id  = "hoeffding_drift_detection_test_w"
    variant_id = "hddm_w_standard"
    library_id = "river"
    delta      = 0.002

# === RIVER WINDOW-BASED METHODS ===
[[detectors]]
    method_id   = "kswin"
    variant_id  = "kswin_standard"
    library_id  = "river"
    alpha       = 0.005
    window_size = 100
    stat_size   = 30

# === ALIBI-DETECT ONLINE METHODS ===
[[detectors]]
    method_id   = "kolmogorov_smirnov"
    variant_id  = "ks_online"
    library_id  = "alibi-detect"
    threshold   = 0.05
    window_size = 100

# === CRAMER-VON MISES ONLINE VARIANT ===
[[detectors]]
    method_id   = "cramer_von_mises"
    variant_id  = "cvm_online"
    library_id  = "alibi-detect"
    threshold   = 0.05
    window_size = 100

# === TEST/VALIDATION DETECTORS ===
[[detectors]]
    method_id  = "periodic_trigger"
    variant_id = "periodic_trigger_standard"
    library_id = "river"
    interval   = 50
