# Adult income dataset with authentic drift based on age
description   = "UCI Adult Income dataset with authentic covariate drift based on age demographics"
source_type   = "uci"
source_name   = "adult"
target_column = "income"
drift_types   = ["covariate"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[0, 48842]]
    drift_intensity      = "moderate"
    expected_effect_size = 0.45
    kl_divergence        = 0.28
    expected_detection   = true
    drift_confidence     = 0.75

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.45
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data: younger adults
[ref_filter]
    sample_range    = [0, 48842]
    feature_filters = [{ column = "age", condition = "<=", value = 30 }]

# Test data: older adults
[test_filter]
    sample_range    = [0, 48842]
    feature_filters = [{ column = "age", condition = ">", value = 50 }]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 48842
    feature_descriptions = [
        "age: Age in years (authentic drift feature)",
        "workclass: Type of employment",
        "education: Education level",
        "education_num: Education in numeric form",
        "marital_status: Marital status",
        "occupation: Type of occupation",
        "relationship: Relationship status",
        "race: Race",
        "sex: Gender",
        "capital_gain: Capital gains",
        "capital_loss: Capital losses",
        "hours_per_week: Hours worked per week",
        "native_country: Native country",
        "income: Income level (<=50K, >50K)",
    ]
    data_quality_score = 0.92
    data_authenticity = "real"
    scientific_traceability = true

# UCI metadata for scientific traceability
[uci_metadata]
    dataset_id             = "adult"
    domain                 = "social_economic"
    original_source        = "Barry Becker, Silicon Graphics"
    acquisition_date       = "1994-01-01"
    collection_methodology = "Census Bureau database extraction"
    data_authenticity      = "real"
    total_instances        = 48842
