# Iris dataset with authentic drift based on petal length
description   = "UCI Iris dataset with authentic covariate drift based on petal length"
source_type   = "uci"
source_name   = "iris"
target_column = "species"
drift_types   = ["covariate"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[0, 150]]
    drift_intensity      = "strong"
    expected_effect_size = 0.85
    kl_divergence        = 0.72
    expected_detection   = true
    drift_confidence     = 0.95

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.85
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data: short petal length flowers
[ref_filter]
    sample_range    = [0, 150]
    feature_filters = [{ column = "petal length", condition = "<=", value = 2.0 }]

# Test data: long petal length flowers
[test_filter]
    sample_range    = [0, 150]
    feature_filters = [{ column = "petal length", condition = ">", value = 4.5 }]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 150
    feature_descriptions = [
        "sepal_length: Sepal length in cm",
        "sepal_width: Sepal width in cm",
        "petal_length: Petal length in cm (authentic drift feature)",
        "petal_width: Petal width in cm",
        "species: Iris species (setosa, versicolor, virginica)",
    ]
    data_quality_score = 1.0
    data_authenticity = "real"
    scientific_traceability = true

# UCI metadata for scientific traceability
[uci_metadata]
    dataset_id             = "iris"
    domain                 = "biology_botany"
    original_source        = "R.A. Fisher"
    acquisition_date       = "1936-01-01"
    collection_methodology = "Manual measurement of iris flowers"
    data_authenticity      = "real"
    total_instances        = 150
