# Wine quality dataset with authentic drift based on alcohol content
description   = "UCI Wine Quality dataset with authentic covariate drift based on alcohol content"
source_type   = "uci"
source_name   = "wine-quality-red"
target_column = "quality"
drift_types   = ["covariate"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[0, 1599]]
    drift_intensity      = "moderate"
    expected_effect_size = 0.58
    kl_divergence        = 0.42
    expected_detection   = true
    drift_confidence     = 0.8

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.58
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data: low alcohol wines (authentic light wine population)
[ref_filter]
    sample_range    = [0, 1599]
    feature_filters = [{ column = "alcohol", condition = "<=", value = 10.5 }]

# Test data: high alcohol wines (authentic strong wine population)
[test_filter]
    sample_range    = [0, 1599]
    feature_filters = [{ column = "alcohol", condition = ">", value = 12.0 }]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 1599
    feature_descriptions = [
        "alcohol: Alcohol content in percentage (authentic drift feature)",
        "quality: Wine quality score (1-10)",
        "volatile_acidity: Volatile acidity level",
        "citric_acid: Citric acid concentration",
        "residual_sugar: Residual sugar content",
        "chlorides: Chloride concentration",
        "free_sulfur_dioxide: Free SO2 concentration",
        "total_sulfur_dioxide: Total SO2 concentration",
        "density: Wine density",
        "pH: pH level",
        "sulphates: Sulphate concentration",
    ]
    data_quality_score = 0.95
    data_authenticity = "real"
    scientific_traceability = true

# UCI metadata for scientific traceability
[uci_metadata]
    dataset_id             = "wine-quality-red"
    domain                 = "food_beverage_chemistry"
    original_source        = "Paulo Cortez, University of Minho"
    acquisition_date       = "2009-10-07"
    collection_methodology = "Laboratory analysis of wine samples"
    data_authenticity      = "real"
    total_instances        = 1599
