[[datasets]]
    path            = "datasets/example.csv"
    format          = "CSV"
    reference_split = 0.5

[[detectors]]
    method_id         = "kolmogorov_smirnov"
    implementation_id = "ks_batch"

[[detectors]]
    method_id         = "cramer_von_mises"
    implementation_id = "cvm_batch"
