# Simple Test Configuration for drift-benchmark
# Tests basic framework functionality with multiple test detectors

# Simple CSV-based scenario for quick testing
[[scenarios]]
    id = "synthetic/concept_drift_gradual"

# Test different drift detection methods with custom implementations
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "evidently"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "evidently"

# Alibi Detect Detectors
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "alibi-detect"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "alibi-detect"

# River Detectors
[[detectors]]
    method_id  = "kswin"
    variant_id = "kswin_standard"
    library_id = "river"
