# Minimal Test Configuration  
# Using only existing detectors to test the framework

[[datasets]]
    path            = "datasets/example.csv"
    format          = "CSV"
    reference_split = 0.5

# Evidently Detectors
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "evidently"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "evidently"

# Alibi Detect Detectors
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "alibi_detect"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "alibi_detect"
