# Minimal Test Configuration  
# Using only existing detectors to test the framework

[[datasets]]
    path            = "datasets/example.csv"
    format          = "csv"
    reference_split = 0.5

# Evidently Detectors
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "evidently"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "evidently"

# Alibi Detect Detectors
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "alibi-detect"

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "alibi-detect"

# River Detectors
[[detectors]]
    method_id  = "kswin"
    variant_id = "kswin_standard"
    library_id = "river"
