# Synthetic Data Comprehensive Benchmark
# Exhaustive evaluation on synthetic scenarios with controlled drift characteristics
# Includes all detector types for comprehensive synthetic data analysis

# All synthetic scenarios with controlled characteristics
[[scenarios]]
    id = "synthetic/covariate_drift_strong"

[[scenarios]]
    id = "synthetic/covariate_drift_weak"

[[scenarios]]
    id = "synthetic/concept_drift_gradual"

[[scenarios]]
    id = "baselines/no_drift_synthetic"

# === EVIDENTLY STATISTICAL TESTS ===
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "anderson_darling"
    variant_id = "ad_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "mann_whitney"
    variant_id = "mw_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "t_test"
    variant_id = "ttest_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "welch_t_test"
    variant_id = "welch_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "epps_singleton"
    variant_id = "epps_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "wasserstein_distance"
    variant_id = "wasserstein_batch"
    library_id = "evidently"
    threshold  = 0.05

# === EVIDENTLY DISTANCE-BASED METHODS ===
[[detectors]]
    method_id  = "jensen_shannon_divergence"
    variant_id = "js_evidently"
    library_id = "evidently"
    threshold  = 0.1

[[detectors]]
    method_id  = "kullback_leibler_divergence"
    variant_id = "kl_evidently"
    library_id = "evidently"
    threshold  = 0.1

[[detectors]]
    method_id  = "chi_square"
    variant_id = "chi_evidently"
    library_id = "evidently"
    threshold  = 0.05

# === ALIBI-DETECT STATISTICAL TESTS ===
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "alibi-detect"
    threshold  = 0.05

[[detectors]]
    method_id  = "cramer_von_mises"
    variant_id = "cvm_batch"
    library_id = "alibi-detect"
    threshold  = 0.05

[[detectors]]
    method_id  = "chi_square"
    variant_id = "chi_batch"
    library_id = "alibi-detect"
    threshold  = 0.05

# === ALIBI-DETECT ONLINE METHODS ===
[[detectors]]
    method_id   = "kolmogorov_smirnov"
    variant_id  = "ks_online"
    library_id  = "alibi-detect"
    threshold   = 0.05
    window_size = 100

# === RIVER STREAMING DETECTORS ===
[[detectors]]
    method_id  = "adaptive_windowing"
    variant_id = "adwin_standard"
    library_id = "river"
    delta      = 0.002

[[detectors]]
    method_id  = "page_hinkley"
    variant_id = "ph_standard"
    library_id = "river"
    delta      = 0.005
    lambda     = 50.0
    alpha      = 0.9999

[[detectors]]
    method_id   = "kswin"
    variant_id  = "kswin_standard"
    library_id  = "river"
    alpha       = 0.005
    window_size = 100
