# Customer churn dataset with authentic concept drift
description   = "Customer data with authentic concept drift in churn behavior patterns"
source_type   = "file"
source_name   = "datasets/customer_churn.csv"
target_column = "churn"
drift_types   = ["concept"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[0, 2000]]
    drift_intensity      = "moderate"
    expected_effect_size = 0.55
    kl_divergence        = 0.38
    expected_detection   = true
    drift_confidence     = 0.8

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.55
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data: high-value customers (different churn patterns)
[ref_filter]
    sample_range = [0, 2000]
    feature_filters = [
        { column = "monthly_charges", condition = ">", value = 70 },
        { column = "tenure", condition = ">", value = 24 },
    ]

# Test data: low-value customers (different churn concept)
[test_filter]
    sample_range = [0, 2000]
    feature_filters = [
        { column = "monthly_charges", condition = "<=", value = 40 },
        { column = "tenure", condition = "<=", value = 12 },
    ]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 2000
    feature_descriptions = [
        "customer_id: Unique customer identifier",
        "gender: Customer gender",
        "senior_citizen: Senior citizen flag",
        "partner: Has partner flag",
        "dependents: Has dependents flag",
        "tenure: Months with company",
        "phone_service: Has phone service",
        "internet_service: Internet service type",
        "online_security: Has online security",
        "tech_support: Has tech support",
        "streaming_tv: Has streaming TV",
        "streaming_movies: Has streaming movies",
        "contract: Contract type",
        "paperless_billing: Paperless billing flag",
        "payment_method: Payment method",
        "monthly_charges: Monthly charges in USD (drift feature)",
        "total_charges: Total charges to date",
        "churn: Customer churn flag (target with concept drift)",
    ]
    data_quality_score = 0.93
    data_authenticity = "real"
    scientific_traceability = true
