# Sensor data with authentic drift patterns
description   = "Industrial sensor data with authentic covariate drift due to equipment aging"
source_type   = "file"
source_name   = "datasets/sensor_data.csv"
target_column = "equipment_status"
drift_types   = ["covariate"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[0, 5000]]
    drift_intensity      = "strong"
    expected_effect_size = 0.72
    kl_divergence        = 0.55
    expected_detection   = true
    drift_confidence     = 0.85

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.72
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data: new equipment (normal operating conditions)
[ref_filter]
    sample_range = [0, 5000]
    feature_filters = [
        { column = "operating_hours", condition = "<=", value = 1000 },
        { column = "temperature", condition = "<=", value = 75 },
    ]

# Test data: aged equipment (degraded operating conditions)
[test_filter]
    sample_range = [0, 5000]
    feature_filters = [
        { column = "operating_hours", condition = ">", value = 5000 },
        { column = "temperature", condition = ">", value = 85 },
    ]

# Enhanced metadata
[enhanced_metadata]
    total_instances = 5000
    feature_descriptions = [
        "timestamp: Recording timestamp",
        "sensor_1: Primary temperature sensor",
        "sensor_2: Secondary temperature sensor",
        "sensor_3: Pressure sensor",
        "sensor_4: Vibration sensor",
        "sensor_5: Humidity sensor",
        "operating_hours: Total operating hours (drift feature)",
        "temperature: Average temperature (drift feature)",
        "pressure: Operating pressure",
        "maintenance_flag: Recent maintenance indicator",
        "equipment_status: Equipment status (normal, warning, critical)",
    ]
    data_quality_score = 0.88
    data_authenticity = "real"
    scientific_traceability = true
