# Synthetic classification with gradual concept drift
description   = "Synthetic classification with gradual concept drift over time"
source_type   = "synthetic"
source_name   = "classification"
target_column = "target"
drift_types   = ["concept"]

# Ground truth specification for evaluation
[ground_truth]
    drift_periods        = [[400, 1000]]
    drift_intensity      = "moderate"
    expected_effect_size = 0.5
    kl_divergence        = 0.35
    expected_detection   = true
    drift_confidence     = 0.75

# Statistical validation for scientific rigor
[statistical_validation]
    expected_effect_size = 0.5
    minimum_power        = 0.80
    significance_level   = 0.05

# Reference data (non-drift period)
[ref_filter]
    sample_range = [0, 400]
    n_samples    = 1000
    n_features   = 6
    n_classes    = 2
    random_state = 42

# Test data (with gradual concept drift)
[test_filter]
    sample_range    = [400, 1000]
    target_shift    = 0.3
    class_imbalance = 0.3
    random_state    = 24

# Enhanced metadata
[enhanced_metadata]
    total_instances = 1000
    feature_descriptions = [
        "feature_1: Primary numerical feature",
        "feature_2: Secondary numerical feature",
        "feature_3: Tertiary numerical feature",
        "feature_4: Quaternary numerical feature",
        "feature_5: Fifth numerical feature",
        "feature_6: Sixth numerical feature",
        "target: Binary classification target with concept drift (0/1)",
    ]
    data_quality_score = 1.0
    data_authenticity = "synthetic"
    scientific_traceability = true
