# Distance and Divergence-Based Methods Configuration
# Comprehensive evaluation of information-theoretic and distance-based drift detection
# Focus on distribution comparison through distance metrics

# Diverse scenarios for distance-based evaluation
[[scenarios]]
    id = "synthetic/covariate_drift_strong"

[[scenarios]]
    id = "synthetic/covariate_drift_weak"

[[scenarios]]
    id = "synthetic/concept_drift_gradual"

[[scenarios]]
    id = "uci/wine_quality_alcohol"

[[scenarios]]
    id = "uci/adult_income_age"

[[scenarios]]
    id = "custom/customer_churn"

[[scenarios]]
    id = "custom/sensor_data_drift"

[[scenarios]]
    id = "baselines/no_drift_synthetic"

# === JENSEN-SHANNON DIVERGENCE ===
[[detectors]]
    method_id  = "jensen_shannon_divergence"
    variant_id = "js_evidently"
    library_id = "evidently"
    threshold  = 0.1

[[detectors]]
    method_id  = "jensen_shannon_divergence"
    variant_id = "js_batch"
    library_id = "scipy"
    threshold  = 0.1

# === KULLBACK-LEIBLER DIVERGENCE ===
[[detectors]]
    method_id  = "kullback_leibler_divergence"
    variant_id = "kl_evidently"
    library_id = "evidently"
    threshold  = 0.1

[[detectors]]
    method_id  = "kullback_leibler_divergence"
    variant_id = "kl_batch"
    library_id = "scipy"
    threshold  = 0.1

# === WASSERSTEIN DISTANCE ===
[[detectors]]
    method_id  = "wasserstein_distance"
    variant_id = "wasserstein_batch"
    library_id = "evidently"
    threshold  = 0.05

# === ALL FEATURES DRIFT DETECTION ===
[[detectors]]
    method_id  = "all_features_drift"
    variant_id = "all_features_evidently"
    library_id = "evidently"
    threshold  = 0.05
    stattest   = "ks"

[[detectors]]
    method_id  = "all_features_drift"
    variant_id = "all_features_evidently"
    library_id = "evidently"
    threshold  = 0.05
    stattest   = "chisquare"

[[detectors]]
    method_id  = "all_features_drift"
    variant_id = "all_features_evidently"
    library_id = "evidently"
    threshold  = 0.05
    stattest   = "jensenshannon"

[[detectors]]
    method_id  = "all_features_drift"
    variant_id = "all_features_batch"
    library_id = "scipy"
    threshold  = 0.05
    stattest   = "ks"

# === SUPPORTING STATISTICAL TESTS FOR COMPARISON ===
[[detectors]]
    method_id  = "kolmogorov_smirnov"
    variant_id = "ks_batch"
    library_id = "evidently"
    threshold  = 0.05

[[detectors]]
    method_id  = "chi_square"
    variant_id = "chi_evidently"
    library_id = "evidently"
    threshold  = 0.05
