# Streaming and Online Drift Detection Configuration
# Comprehensive evaluation of all streaming/online drift detection methods
# Focus on concept drift detection in data streams using River library

# Scenarios appropriate for streaming and concept drift detection
[[scenarios]]
    id = "synthetic/concept_drift_gradual"

[[scenarios]]
    id = "synthetic/covariate_drift_strong"

# === ADAPTIVE WINDOWING METHODS ===
[[detectors]]
    method_id  = "adaptive_windowing"
    variant_id = "adwin_standard"
    library_id = "river"
    delta      = 0.002

# === PAGE-HINKLEY TEST ===
[[detectors]]
    method_id  = "page_hinkley"
    variant_id = "ph_standard"
    library_id = "river"
    delta      = 0.005
    lambda     = 50.0
    alpha      = 0.9999

# === KOLMOGOROV-SMIRNOV WINDOWING (KSWIN) ===
[[detectors]]
    method_id   = "kswin"
    variant_id  = "kswin_standard"
    library_id  = "river"
    alpha       = 0.005
    window_size = 100
    stat_size   = 30

# === STATISTICAL PROCESS CONTROL METHODS ===
[[detectors]]
    method_id       = "cusum"
    variant_id      = "cusum_standard"
    library_id      = "river"
    threshold       = 0.5
    drift_threshold = 1.0

[[detectors]]
    method_id  = "geometric_moving_average"
    variant_id = "gma_standard"
    library_id = "river"
    lambda     = 0.1
    threshold  = 0.5

[[detectors]]
    method_id  = "exponential_cumulative_drift"
    variant_id = "ecdd_standard"
    library_id = "river"
    lambda     = 0.1
    threshold  = 0.5

[[detectors]]
    method_id         = "ewma_concept"
    variant_id        = "ewma_standard"
    library_id        = "river"
    lambda            = 0.1
    warning_threshold = 2.0
    drift_threshold   = 3.0

# === ONLINE VARIANTS FROM ALIBI-DETECT ===
[[detectors]]
    method_id   = "kolmogorov_smirnov"
    variant_id  = "ks_online"
    library_id  = "alibi-detect"
    threshold   = 0.05
    window_size = 100

# === TEST DETECTOR FOR VALIDATION ===
[[detectors]]
    method_id  = "periodic_trigger"
    variant_id = "periodic_trigger_standard"
    library_id = "river"
    interval   = 50
